server:
  port: 8081

spring:
  application:
    name: rag-pipeline
  main:
    banner-mode: off
    log-startup-info: false

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com
      chat:
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
      embedding:
        base-url: https://generativelanguage.googleapis.com
        api-key: ${GEMINI_API_KEY}
        embeddings-path: /v1beta/openai/embeddings
        options:
          model: gemini-embedding-exp-03-07
          dimensions: 768
    vectorstore:
      neo4j:
        index-name: spring-ai-document-index
        embedding-dimension: 768
        initialize-schema: true
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: Admin@123
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

